// Automatically generated by MockGen. DO NOT EDIT!
// Source: api/api.go

package api_mocks

import (
	gomock "github.com/golang/mock/gomock"
	"github.com/cloud-ca/go-cloudca/api"
)

// Mock of CcaClient interface
type MockCcaClient struct {
	ctrl     *gomock.Controller
	recorder *_MockCcaClientRecorder
}

// Recorder for MockCcaClient (not exported)
type _MockCcaClientRecorder struct {
	mock *MockCcaClient
}

func NewMockCcaClient(ctrl *gomock.Controller) *MockCcaClient {
	mock := &MockCcaClient{ctrl: ctrl}
	mock.recorder = &_MockCcaClientRecorder{mock}
	return mock
}

func (_m *MockCcaClient) EXPECT() *_MockCcaClientRecorder {
	return _m.recorder
}

func (_m *MockCcaClient) Do(request api.CcaRequest) (*api.CcaResponse, error) {
	ret := _m.ctrl.Call(_m, "Do", request)
	ret0, _ := ret[0].(*api.CcaResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCcaClientRecorder) Do(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Do", arg0)
}
